[EI-191] [web] refactor: Refactor searchedIndicatorList in source-indicator-search-list
Fingoo-org/Fingoo pull request #152
Opened 2024-03-28 01:40 UTC by swgvenghy

## ✅ 작업 내용
searchIndicatorList 함수 return 부분 분리하였습니다.

## 🤔 고민 했던 부분
해당 부분을 searchedIndicatorList 함수 외부로 분리를 해야하나에 대해서 고민했습니다.
하지만 메모이제이션된 값을 밖으로 빼는 것이 효율에 있어 부정적이라 판단하고 해당 함수 내부에서만 분리하도록 하였습니다.

## 🔊 도움이 필요한 부분
- 도움이 필요한 부분이 없다면 **삭제** 해도 됩니다.
- **팀원들의 의견이 꼭 필요한 부분**을 작성해주세요.
- **팀원들은 놓치지 않고 꼭 이 항목을 보고 의견을 주세요.**

2024-03-28 05:23 UTC, seonghunYang requested changes

2024-03-28 05:23 UTC, seonghunYang commented on web/app/ui/components/numerical-guidance/custom-forecast-indicator/source-indicator-search-list.tsx
> +    const upperSearchTerm = searchTerm.toLocaleUpperCase();
[comment]
- 인라인 함수를 임시 변수로 바꾸는 것이 리팩토링이라고 말하기는 어려울 것 같아요. 그 이유는 인라인 함수가 임시 변수보다 가독성이 더 좋다고 생각하기 때문입니다.

2024-03-28 05:23 UTC, seonghunYang commented on web/app/ui/components/numerical-guidance/custom-forecast-indicator/source-indicator-search-list.tsx
> +        indicator.ticker.toLocaleUpperCase().includes(upperSearchTerm)
[request change]
- 최종적으로 리팩토링을 하려면, 이 return 부분은 모두 함수로 만들어 추상화해야 할 것 같아요. 해당 부분의 코드가 한눈에 보기에 어떤 기능을 하는지 파악하기 어렵기 때문입니다. 물론 복잡하지 않아서 자세히 보면 어떤 역할을 하는지 알 수 있지만, 이를 추상화하여 선언적으로 표현해주면, 읽는 사람이 이를 파악하는 데 들이는 수고를 줄일 수 있을 거에요

2024-03-28 07:55 UTC, swgvenghy commented on web/app/ui/components/numerical-guidance/custom-forecast-indicator/source-indicator-search-list.tsx
> +        indicator.ticker.toLocaleUpperCase().includes(upperSearchTerm)
[d2f7536](https://github.com/Fingoo-org/Fingoo/pull/152/commits/d2f75369bd2696b82fbde82c49292d2afab5480b)

2024-03-28 08:00 UTC, swgvenghy commented on web/app/ui/components/numerical-guidance/custom-forecast-indicator/source-indicator-search-list.tsx
> +        indicator.ticker.toLocaleUpperCase().includes(upperSearchTerm)
변경 과정에서 Name과 Ticker의 이름이 겹치지 않을 것이라는 판단을 내렸었습니다. 하여 다음처럼 코드를 수정했었는데 중복이 된다면 어떤 방법으로 해결해야할지 궁금합니다...!

2024-03-28 10:28 UTC, seonghunYang requested changes
수고하셨어요. hook으로 뺸 아이디어는 정말 좋네요

2024-03-28 10:28 UTC, seonghunYang commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
[comment]
- 훅으로 분리하는 것은 좋은 생각이네요. 검색 지표 리스트는 다양한 곳에서 활용될 수 있으므로, 훅으로 분리하면 유용하겠네요. 좋습니다!
- 파일 위치는 custom-forecast-indicator보다는 indicator 아래가 더 적절해 보입니다. 혹시 이 이유에 대해 이해가 가지 않으면 알려주세요.

2024-03-28 10:28 UTC, seonghunYang commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
> +  const { indicatorList } = useIndicatorList();
[request change]
- 이 경우에는 useIndicatorList 훅보다는 하위 계층인 useFetchIndicatorList() 훅을 사용하는 것이 더 좋아 보입니다. 가능한 경우, 같은 계층보다는 하위 계층과 결합하는 것이 더 바람직하기 때문입니다.

2024-03-28 10:28 UTC, seonghunYang commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
> +  }, [indicatorList, upperSearchTerm]);
[request change]
- 이렇게 분리하는 것이 좋아 보이진 않네요. 검색어가 없어도 필터를 무조건 거치는 단점도 있습니다. 지표 리스트는 상황에 따라 길어질 수 있으므로, 가능한 한 순회를 줄이는 것이 바람직해 보입니다.
- filter 순회는 한번만 돌고, 검색 로직만 추상화시키는 건 어떨까요?

2024-03-28 10:28 UTC, seonghunYang commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
> +    if (indicatorNameIncludes === undefined || indicatorTickerIncludes === undefined) return undefined;
[request change]
- 검색된 값이 없으면 빈객체를 return하는게 더 적절한 것 같습니다

2024-03-28 10:28 UTC, seonghunYang commented on web/app/ui/components/numerical-guidance/custom-forecast-indicator/source-indicator-search-list.tsx
> +  const searchedIndicatorList = useIndicatorSearchList(searchTerm);
[request change]
- 훅은 안정성을 위해 최상단에 위치하는게 좋으므로 useState 바로 아래로 변경하는게 좋아보입니다

2024-03-28 11:47 UTC, swgvenghy commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
> +  const { indicatorList } = useIndicatorList();
[56279d5](https://github.com/Fingoo-org/Fingoo/pull/152/commits/56279d5838b46ec0d514f86495b1df139763652d)

2024-03-28 11:52 UTC, swgvenghy commented on web/app/business/hooks/custom-forecast-indicator/use-indicator-search-list.hooks.ts
custom-forecast-indicator 폴더는 custom-forcast-indicator에 대해 확인 및 관리하는 폴더이고 해당 훅은 indicator의 검색과 관련된 훅이기에 custom-forecast-indicator보다 indicator를 확인하고 관리하는 indicator 폴더에 더 어울리기에 indicator 아래가 적절하다고 생각했습니다.
혹시 다른 이유에서 indicator 아래가 적절하다면 이유가 궁금합니다!

2024-03-29 05:54 UTC, seonghunYang requested changes

2024-03-29 05:54 UTC, seonghunYang commented on web/app/business/hooks/indicator/use-indicator-search-list.hooks.ts
> +
[request change]
- 함수에 맞게 동사형 네이밍이 들어가야할 것 같아요

2024-03-29 05:54 UTC, seonghunYang commented on web/app/business/hooks/indicator/use-indicator-search-list.hooks.ts
> +  }, [indicatorList, searchTerm]);
[request change]
- indicatorIncludeSearch 함수에 대한 의존성도 추가해야할 것 같네요.
- 덧붙여 렌더링마다 함수가 재생성되는 것을 막기 위해 useCallback을 활용해야할 것 같습니다

2024-03-29 06:22 UTC, swgvenghy commented on web/app/business/hooks/indicator/use-indicator-search-list.hooks.ts
> +
[4273cf6](https://github.com/Fingoo-org/Fingoo/pull/152/commits/4273cf6c9f8a80f761eb7afbbf3bcf27f47173ae)

2024-03-29 08:05 UTC, seonghunYang approved these changes
- 수고하셨어요. 좋은 훅이 나온 것 같네요!

2024-03-29 08:09 UTC, swgvenghy commented
> - 수고하셨어요. 좋은 훅이 나온 것 같네요!

감사합니다!!

2024-03-29 08:09 UTC, merged