Ei 201
Fingoo-org/Fingoo pull request #208
Opened 2024-05-08 17:14 UTC by yoounyoungheon

## ✅ 작업 내용
- 예측지표의 타겟지표와 재료지표 도메인을 수정했습니다.
- 타겟지표는 지표 아이디와 타입을 요청받으면 핸들러에서 지표를 그대로 호출해 예측지표가 타겟지표에대한 정보를 가지고 있을 수 있도록 수정했습니다.
- 재료지표는 지표 아이디와 타입 가중치를 요청받으면 핸들러에서 지표를 불러와서 가중치까지 추가해 예측제표가 재료지표 + 가중치에대한 정보를 가질 수 있도록 구현했습니다. 기존 지표에 가중치를 가지고 있는 dto가 없었기에 처음에는 any타입으로 지정했다가 추후 문제가 생길 수 있다는 점을 고려했습니다. 그래서 기존 stock, funds 등 각 지표 dto를 상속해 SourceStockDto 등을 만들어주고 이를 SourceIndicatorDtoType으로 묶어서 관리할 수 있게 구현했습니다.
- 그레인저, 공적분 검정에서 예외처리가 미흡한 점을 발견해 통계적인 이슈로 statsmodel 라이브러리에서 지정한 오류가 발생하면 무조건 ['검정 결과를 확인할 수 없습니다.']가 오게끔 조치했습니다.

2024-05-09 05:11 UTC, Hoya324 reviewed
수고하셨습니다 몇개만 수정해주시면 될거 같아요!

2024-05-09 05:11 UTC, Hoya324 commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/dto/source-indicator.dto.ts
이 파일에 모든걸 모아두는게 맞는지 따로 분리하는게 맞을지 고민해볼 필요가 있어보입니다.! @yoounyoungheon 의견 한번만 남겨주세요!

2024-05-09 05:11 UTC, Hoya324 commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/mapper/indicator-dto-type-to-source-indicator-dto-type.mapper.ts
[Request Change]

클래스명에 동작에 대한 정의가 너무 자세히 들어가 있습니다! SourceIndicatorMapper 이 더 적절한거 같습니다!

2024-05-09 05:11 UTC, Hoya324 commented on api/src/numerical-guidance/application/query/custom-forecast-indicator/get-custom-forecast-indicator/get-custom-forecast-indicator.query.handler.ts
> +    console.log(customForecastIndicator.targetIndicator);
[Request Change]

log 찍었던거 지워주세요!

2024-05-09 06:24 UTC, seonghunYang requested changes
- 영헌씨 이거 가중치 수정하려면 그전처럼 아이디랑 가중치만 보내주면 되는건가요 아니면 정보 다 보내줘야 하나요?

2024-05-09 06:24 UTC, seonghunYang commented on api/src/numerical-guidance/api/custom-forecast-indicator/custom-forecast-indicator.controller.ts
> +      updateSourceIndicatorsAndWeightsDto.sourceIndicatorsRequestInformation,
- request information 이라는 용어를 봤을 때 어떤 의미인지 들어나지 않는 것 같은데, 변경한 의도를 알 수 있을까요?

2024-05-09 06:24 UTC, seonghunYang commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/dto/source-indicator.dto.ts
- 우선 중복이 너무 많아보입니다. 생성자로 받는 인자를 지금 다 풀어져있는데, weight만 추가하는거라면 인자를 묶어서 받고 super에 바로 전달하는 방식으로 전환이 필요해보여요
- 이렇게 중복을 제거하면 코드양이 확 줄어드니까, 한 파일에다가 모아 두는건 괜찮아보입니다

2024-05-10 09:39 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/update-source-indicators-information.command.handler.ts
> +    customForecastIndicator.updateSourceIndicatorsInformation(sourceIndicatorsInformation);
745ce63afd3f55a845445110bffd5601dbd17c8a 수정했습니다 !

2024-05-10 09:39 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/mapper/indicator-dto-type-to-source-indicator-dto-type.mapper.ts
745ce63afd3f55a845445110bffd5601dbd17c8a 수정했습니다 !

2024-05-10 09:43 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/query/custom-forecast-indicator/get-custom-forecast-indicator/get-custom-forecast-indicator.query.handler.ts
> +    console.log(customForecastIndicator.targetIndicator);
9cb374b62db180b040e83f4f27bacca0ed3e7dcd 수정했습니다 !

2024-05-10 09:47 UTC, yoounyoungheon commented on api/src/numerical-guidance/api/custom-forecast-indicator/custom-forecast-indicator.controller.ts
> +      updateSourceIndicatorsAndWeightsDto.sourceIndicatorsRequestInformation,
request Information은 클라이언트가 보내는 요청으로 기존과 동일하게 id, weight, type 으로 정의되어있습니다.
request information을 바탕으로 핸들러에서 LoadIndicatorPort를 호출해 재료지표 정보들을 불러와 예측지표 도메인을 생성해줍니다 !

2024-05-10 11:18 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/dto/source-indicator.dto.ts
그러면 sourceIndicatorInformation {weight:string, id:string, indicatorType:string} 형식은 이렇게 유지하고 따로 sourceIndicator {id: string, market: string ... }이렇게 말씀이신가요?

2024-05-11 18:03 UTC, yoounyoungheon commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/dto/source-indicator.dto.ts
5d447e2a011cb7f4d8fc3faa182c0a74e6203883 수정했습니다 !

2024-05-12 02:38 UTC, Hoya324 commented on api/src/numerical-guidance/application/command/custom-forecast-indicator/update-source-indicators-and-weights/update-source-indicators-information.command.handler.ts
> +    customForecastIndicator.updateSourceIndicatorsInformation(sourceIndicatorsInformation);
메서드명을 바꾸라는게 아니었습니다! 

```ts
const sourceIndicatorsInformation: SourceIndicatorDtoType[] = [];

    for (const sourceIndicatorInformation of sourceIndicatorsRequestInformation) {
      const sourceIndicatorId = sourceIndicatorInformation.sourceIndicatorId;
      const sourceIndicatorType = sourceIndicatorInformation.indicatorType;
      const sourceIndicator = await this.loadIndicatorPort.loadIndicator(sourceIndicatorId, sourceIndicatorType);

      const sourceIndicatorDtoType: SourceIndicatorDtoType =
        IndicatorDtoToSourceIndicatorDtoMapper.mapIndicatorDtoTypeToSourceIndicatorDtoType(
          sourceIndicator,
          sourceIndicatorInformation.weight,
        );

      sourceIndicatorsInformation.push(sourceIndicatorDtoType);
    }
    console.log(sourceIndicatorsInformation);
    customForecastIndicator.updateSourceIndicatorsInformation(sourceIndicatorsInformation);
```
이 부분을 클래스 맨 아래에 private 메서드로 빼서 사용해달라는 요청이었어요! 그리고 console.log도 빼주세요!

2024-05-13 07:08 UTC, seonghunYang approved these changes

2024-05-13 07:08 UTC, merged