[Ei 999] view mode
Fingoo-org/Fingoo pull request #275
Opened 2024-08-03 22:07 UTC by yesolz

## ✅ 작업 내용
- 오타 수정: collpase → collapsed, relatvie → relative 오타 수정.
- 아이콘 업데이트: 화면 분할의 Full 아이콘을 새롭게 디자인하고, 기존 Full 아이콘을 뷰 모드 아이콘으로 사용.
- 뷰 모드 전역 상태 추가: 뷰 모드를 관리하는 전역 상태를 추가하여 UI 동기화를 개선.
- 사이드바 상태 관리 변경: 양쪽 사이드바(sideNavbar, chatbotSidebar)의 collapsed 상태를 전역으로 관리하도록 변경.
- IconButton 정렬 수정: 아이콘 버튼 내부의 아이콘을 가운데 정렬하여 클릭 영역 불일치 문제를 해결하고, 뷰 모드 버튼과의 정렬을 일관되게 유지.

## 🤔 고민 했던 부분
- 뷰 모드 상태 분리 및 전역 관리: 양쪽 사이드바의 상태를 전역으로 관리함으로써, 모든 사이드바가 닫힌 경우에 뷰 모드를 활성화하도록 설정하였습니다. 각 사이드바 상태를 따로 관리하면서 동기화하는 것보다 전역 상태를 공유하여 일관성을 유지하는 것이 더 효과적이라고 판단했습니다.
- IconButton의 정렬 문제: 공유 아이콘과 버튼의 클릭 영역이 불일치하는 문제가 있었습니다. 아이콘의 가운데 정렬을 통해 기존의 클릭 문제를 해결하고, 뷰 모드 아이콘과의 시각적 일관성을 유지하였습니다.

## 🔊 도움이 필요한 부분
- 전역 상태 관리 및 UI 변경 사항이 현재 아키텍처와 잘 맞는지 검토 부탁드립니다.

2024-08-04 03:36 UTC, seonghunYang requested changes

2024-08-04 03:36 UTC, seonghunYang commented on apps/web/app/business/hooks/use-viewmode.hook.ts
- 파일 네이밍 use-view-mode가 더 적절할 것 같습니다

2024-08-04 03:36 UTC, seonghunYang commented on apps/web/app/store/stores/viewmode.store.ts
> +    }));
- viewMode 값을 변경할 때마다 동기화를 시키면 데이터 중복 문제가 발생할 수 있습니다. 따라서, isViewMode 값은 use-view-model 훅에서 sideNavbarCollapsed와 chatbotSidebarCollapsed 값을 이용해 계산하는 것이 어떨까요?.

- 데이터 중복 문제에 대해서는 아래 자료를 참고해주세요!
https://ko.react.dev/learn/choosing-the-state-structure#avoid-redundant-state

2024-08-04 03:36 UTC, seonghunYang commented on apps/web/app/ui/components/domain/numerical-guidance/indicator-board/indicator-board.tsx
> +              <IconButton icon={ViewModeIcon} className="cursor-pointer" onClick={enableViewMode} color="gray" />
- indicator-board 컴포넌트의 역할이 너무 많으니, 뷰 모드를 전담하는 컴포넌트를 만들어 뷰모드 관련 내용을 캡슐화하면 어떨까요?
- 예를 들어, MetadataSharePopover 컴포넌트처럼 view-mode-trigger-button이라는 도메인 컴포넌트를 만들어 관련 내용을 해당 컴포넌트로 옮기고, indicator-board는 view-mode-trigger-button을 호출하기만 하는거죠!

2024-08-04 03:36 UTC, seonghunYang commented on apps/web/app/ui/components/view/atom/viewmode-icon.tsx
혹시 저희가 이미 사용 중인 radix-icon이나 hero-icon v1에 유사한 아이콘이 있는지 확인해보셨을까요? 만약 있다면, 해당 아이콘으로 변경하는 것이 좋을 것 같습니다.
- radix: https://www.radix-ui.com/icons
- hero: https://v1.heroicons.com/

2024-08-04 03:36 UTC, seonghunYang commented on apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
> +  const { sideNavbarCollapsed, setSideNavbarCollapsed } = useViewModeStore();
- 이 부분이 중요한 포인트인데, 해당 side-navigation-bar 컴포넌트는 view 컴포넌트로, view mode와 같은 비즈니스 로직을 알면 안 됩니다. 그렇게 되면 뷰 컴포넌트를 재사용하기 어려워지기 때문입니다. 따라서 sideNavbarCollapsed와 같은 데이터를 내부가 아닌 외부에서 호출 시 prop으로 전달받아야 합니다.

- 이를 위해서는 해당 컴포넌트가 제어 가능해야 하는데, 지금은 비제어 컴포넌트이므로 외부에서 값을 받아도 동작할 수 있게 제어/비제어가 가능하게 만들어야 합니다. 그래서 저번에 useControlled와 같은 훅을 참조해 달라고 말씀드렸습니다.

- 조금 어려울 수 있지만, 굉장히 재미있는 내용이니 아래 자료를 참고해 보시면 좋을 것 같습니다. 직접 수정해 보시고, 어려운 부분이나 막히는 부분이 있으면 말씀해 주세요. 같이 해결해 봅시다.

https://fe-developers.kakaoent.com/2022/221110-ioc-pattern/

2024-08-04 03:38 UTC, seonghunYang requested changes
수고 많으셨습니다. 전반적으로 잘해주셔서 잘 따라오고 계시다는 생각이 드네요! 몇 가지 중요한 포인트와 지켜야 할 내용들 위주로 개선사항을 작성해봤습니다. 만약 도움이 필요한 부분이 있으시면 언제든 말씀해주세요!

2024-08-06 14:02 UTC, yesolz commented on apps/web/app/business/hooks/use-viewmode.hook.ts
https://github.com/Fingoo-org/Fingoo/pull/275/commits/36c2d2991bd8ba087266ef28b40261441896fbc8

2024-08-06 14:02 UTC, yesolz commented on apps/web/app/ui/components/view/atom/viewmode-icon.tsx
https://github.com/Fingoo-org/Fingoo/pull/275/commits/2060e5a723e097de43952e361d3f8e3c5ccc37f8

2024-08-06 14:03 UTC, yesolz commented on apps/web/app/ui/components/domain/numerical-guidance/indicator-board/indicator-board.tsx
> +              <IconButton icon={ViewModeIcon} className="cursor-pointer" onClick={enableViewMode} color="gray" />
https://github.com/Fingoo-org/Fingoo/pull/275/commits/3d46dfdd352b82b3aa1212125cbe8bdf0d45203b

2024-08-06 14:03 UTC, yesolz commented on apps/web/app/store/stores/viewmode.store.ts
> +    }));
https://github.com/Fingoo-org/Fingoo/pull/275/commits/5edb78b57d5f31b375949583efd1013cac560bb1

2024-08-06 14:04 UTC, yesolz commented on apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
> +  const { sideNavbarCollapsed, setSideNavbarCollapsed } = useViewModeStore();
https://github.com/Fingoo-org/Fingoo/pull/275/commits/ea4b904d0c45c7e26f539e7f783f7d61981d32f5

2024-08-07 03:24 UTC, seonghunYang reviewed
- 수고하셨습니다. 남겨드린 사항에 대한 의견 남겨주시고, 수정 여부를 결정해봅시다.

2024-08-07 03:24 UTC, seonghunYang commented on apps/web/app/ui/pages/workspace/chat-ai-navigator.tsx
> +    setChatbotSidebarCollapsed(!chatbotSidebarCollapsed);
- 만약 뷰 모델이 비즈니스 로직이라면, use-view-model을 참조하고 chat-ai-navigator 컴포넌트를 도메인 컴포넌트로 재구조화하는게 어떨까요?

2024-08-07 03:40 UTC, yesolz commented on apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
> +  const { sideNavbarCollapsed, setSideNavbarCollapsed } = useViewModeStore();
첨부해주신 카카오 블로그의 제어 컴포넌트 예제의 경우 useRef를 통해 isControlled 값을 초기 렌더링 시 고정하는 것 같은데요, 이전에 보내주신 useControlled 훅의 경우 useRef가 사용되지 않고 있어, isControlled 값이 변경될 수 있다는 것을 고려하여 작성하신 것인지 궁금합니다.

제가 이해한 바로는,
- side-navigation-bar-root 컴포넌트를 제어, 비제어 둘다 가능하게 하는 이유는 현재는 제어 컴포넌트로 사용되지만, 비제어로도 가능하게 함으로써 재사용성을 높이기 위한 것
- 제어/비제어 여부는 초기 렌더링 시 결정되므로 useRef를 사용한다

이렇게 생각했는데, 맞게 이해한 것인지 확인 부탁드립니다!

2024-08-07 03:41 UTC, yesolz commented on apps/web/app/utils/hooks/use-controlled.hook.ts
- 비즈니스 로직을 다루는 훅은 아니라는 생각이 들어 utils/hooks에 넣어두었는데, 적절한 위치인지 궁금합니다.

2024-08-07 03:51 UTC, yesolz commented on apps/web/app/ui/components/domain/numerical-guidance/indicator-board/view-mode-trigger-button.tsx
- 뷰 모드 도메인을 numerical-guidance로 봐야할까요?
- view-mode-trigger-button을 작성하면서, indicator-board 디렉토리에 해당 컴포넌트를 추가했습니다.
- 기존에 use-view-mode.hook.ts와 viewmode.store.ts는 아래와 같이 도메인에 속하지 않게 설정해두었어서, 디렉토리 변경이 필요할 거 같아 질문드립니다!
    - apps/web/app/business/hooks/use-view-mode.hook.ts
    - apps/web/app/store/stores/viewmode.store.ts

2024-08-07 03:56 UTC, seonghunYang commented
안녕하세요 예솔님. 오늘도 너무 좋은 질문들을 많이 해주셨네요. PR은 답변 후 바로 확인해보겠습니다

질문의 의도가 충분히 이해됩니다. 뷰 모드는 뷰 로직과 비즈니스 로직의 경계에 위치하고 있다고 생각합니다. 이는 기본적으로 UI 사이드바를 열고 닫는 상태를 조작하기 때문입니다. 제 관점에서 비즈니스 로직의 기준은 해당 기능이 비즈니스 가치를 창출하는지 여부입니다. 즉, 이 뷰 모드가 단순히 편의성을 위한 기능인지, 아니면 비즈니스 수단인지가 중요한 판단의 기준이라고 볼 수 있습니다.
 
 주간 회의에서 영업부가 뷰 모드에 대한 데이터를 수집하고, 이를 토대로 프로 모델 기준을 설정하는 것을 고려하면, 뷰 모드는 단순한 편의성 기능을 넘어 비즈니스 가치를 창출하는 기능으로 볼 수 있습니다. 따라서, 현 상황에서는 뷰 모드를 numerical-guidance 도메인 로직에 포함시키는 것이 적절하다고 생각합니다.
 
 물론 이는 절대적인 기준이 아닙니다. 추후 뷰 모드가 비즈니스 가치를 창출하지 않고 단순히 편의성 기능으로 인식된다면, 그때는 UI 로직으로 위치를 변경하는 것이 적절할 것입니다. 이처럼 소프트웨어는 유연하게 설계하는 것이 중요하다는게 제 생각입니다.

네, 정확합니다. 비즈니스 훅이 아닌 경우, 예를 들어 뷰 로직이나 use-controlled과 같은 기술적인 훅은 현재 utils/hooks에 넣어 비즈니스 훅과 구분하고 있습니다.

저번에 보내드린 use-controlled.hook은 카카오 블로그의 코드를 약간 변형한 것입니다. 말씀하신 대로, ‘제어/비제어 여부는 초기 렌더링 시 결정되므로 useRef를 사용한다’는 접근 방식이 사이드 이펙트를 일으키고 예기치 못한 동작을 유발할 수 있다고 판단하여 수정을 거쳤습니다.
 
 제어 → 비제어 혹은 비제어 → 제어로의 전환이 빈번하지는 않겠지만, use-controlled 훅이 이를 제한할 필요는 없다고 생각합니다. 이러한 상황에서 useRef가 사용되면 호출자가 예상하지 못한 동작이 발생할 수 있고, 이로 인해 내부 코드를 살펴봐야 하는 상황이 생길 수 있습니다.
 
 따라서 use-controlled 훅은 순수한 형태로 유지하는 것이 더 적절하다고 판단하여 useRef를 제거했습니다.
 
 즉 side-navigation-bar-root 컴포넌트를 제어, 비제어 둘다 가능하게 하는 이유는 현재는 제어 컴포넌트로 사용되지만, 비제어로도 가능하게 함으로써 재사용성을 높이기 위한 것 → 이것은 맞고 
 
 제어/비제어 여부는 초기 렌더링 시 결정되므로 useRef를 사용한다 → 이것은 제가 의도한 바가 아니라고 할 수 있을 것 같습니다.

2024-08-14 13:42 UTC, yesolz commented
뷰 모드는 뷰 로직과 비즈니스 로직의 경계에 있으며, 현재 이 기능이 비즈니스 가치를 창출하기 때문에 도메인 로직에 포함해야한다는 점은 이해하였습니다.

하지만 뷰 모드를 numerical-guidance 도메인쪽으로 포함시키는 것이 맞는지에 대해서는 다시 의문이 듭니다. 현재 뷰 모드 전환은 좌측과 우측 사이드바를 닫는 것인데, 우측에는 linguistic-guidance 도메인의 채팅 기능이 위치해있기 때문입니다.

이에 대해 어떻게 생각하시는지, 그리고 이러한 관점에서 chat-ai-navigator 컴포넌트를 도메인 컴포넌트로 재구조화 해야한다면 어떤 식으로 하면 좋을지 묻고 싶습니다!

2024-08-15 00:26 UTC, seonghunYang commented
> 뷰 모드는 뷰 로직과 비즈니스 로직의 경계에 있으며, 현재 이 기능이 비즈니스 가치를 창출하기 때문에 도메인 로직에 포함해야한다는 점은 이해하였습니다.
> 
> 
> 
> 하지만 뷰 모드를 numerical-guidance 도메인쪽으로 포함시키는 것이 맞는지에 대해서는 다시 의문이 듭니다. 현재 뷰 모드 전환은 좌측과 우측 사이드바를 닫는 것인데, 우측에는 linguistic-guidance 도메인의 채팅 기능이 위치해있기 때문입니다.
> 
> 
> 
> 이에 대해 어떻게 생각하시는지, 그리고 이러한 관점에서 chat-ai-navigator 컴포넌트를 도메인 컴포넌트로 재구조화 해야한다면 어떤 식으로 하면 좋을지 묻고 싶습니다!

말씀하신 대로, 뷰 모드를 numeric-guidance 도메인에 포함시키는 것은 적절하지 않은 것 같습니다. 예솔님 말씀을 들어보니, 원래대로 뷰 로직으로 다루는 것이 더 적절할 것 같습니다. 좋은 지적 감사합니다!

혹시 남은 변경사항이 있을까요? 문제가 없다면 병합을 진행하려고 합니다.

2024-08-16 00:41 UTC, yesolz commented
남은 변경사항 없습니다! 감사합니다 :)

2024-08-18 14:50 UTC, merged