[MC-4] feat: Indicator quote card component
Fingoo-org/Fingoo pull request #282
Opened 2024-09-11 12:27 UTC by swgvenghy

## ✅ 작업 내용
- Indicator quote api와 연동되는 도메인 컴포넌트 제작하였습니다.
- MSW연동하였습니다.

2024-09-20 12:30 UTC, seonghunYang requested changes
수고하셨습니다! MSW를 제가 간단하게 설명했던 것 같은데, 잘 사용해주셨네요.

남겨주신 리뷰 내용은 개발자로서 고민해보면 좋은 지점들이라고 생각합니다. 한번 검토해보시고 필요한 부분을 수정해주시면 좋겠습니다.

텍스트로 전달하는 데에는 한계가 있을 것 같습니다. 만약 이해가 잘안간다면  언제든 연락해주세요! 보이스로 자세히 설명해드리겠습니다.

2024-09-20 12:30 UTC, seonghunYang commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +  }, [indicatorQuoteData]);
[request change]
여기 부분은 값이 없을 때 초기값을 지정하는 것인가요? 제 생각에는 훅이 undefined일 때 그 값을 그대로 전달하고, 컴포넌트에서 값이 아직 도착하지 않은 상태를 처리하는 것이 더 좋을 것 같습니다.

해당 훅이 컴포넌트의 존재를 알고 이에 맞춰 값을 처리하면, 실제로는 의존성이 없어도 있는 것처럼 되어 재사용성이 떨어집니다. 훅은 어떤 컴포넌트가 자신을 사용할지 모르기 때문에, 단순히 값만 전달하고 컴포넌트에서 useMemo를 적용하는 것이 바람직해 보입니다

2024-09-20 12:30 UTC, seonghunYang commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +export const useIndicatorQuote = (request: IndicatorQuoteRequest) => {
훅의 request 객체는 어디서 주입받는 걸까요? 이 훅을 사용하는 IndicatorQuoteAnalytics 컴포넌트도 IndicatorQuoteRequest 객체를 외부에서 주입받고 있는데, 주입해주는 컴포넌트가 보이지 않습니다.

또한, queryparams가 매우 많고 일부는 기본값을 상수로 지정해야 할 것 같은데, 이 훅이 그 역할을 해야 한다고 생각합니다. 그렇다면 실제 사용 시 모든 request 객체를 외부에서 주입받아야 하는지, 아니면 이 훅 내부에서 일부 처리할 수 있는지 고려해보면 좋겠습니다.

2024-09-22 11:16 UTC, swgvenghy commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +  }, [indicatorQuoteData]);
undefined를 전달하고 컴포넌트에서 undefined일 때 아무것도 나오지 않도록 하였습니다! 컴포넌트에서 useMemo를 적용하는 부분이 약간 이해가 안되는데 혹시 추가적으로 설명해주실 수 있을까요?!
[9b4c908](https://github.com/Fingoo-org/Fingoo/pull/282/commits/9b4c908f00d1c68c26d0b2bf934eec1114a26350)

2024-09-22 12:56 UTC, swgvenghy commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +export const useIndicatorQuote = (request: IndicatorQuoteRequest) => {
MC-4와 연결되는 부분에서 Request 객체를 주입한다고 생각했습니다. 다만 해당 부분에서 어떤 값이 올지, 그리고 이후에 어떻게 처리를 해야할지 감이 안와서 일단 전체 객체를 넣어놨었습니다. indicatorType과 id가 들어올 것이라고 생각하고 훅 내부 처리 고민해보고 반영하겠습니다!

2024-09-26 08:55 UTC, seonghunYang commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +  }, [indicatorQuoteData]);
- 현재 formattedIndicatorQuote를 만들 때 undefined면 0과 같은 값으로 초기화된 객체들을 전달하고 있어서, undefined가 전달되지 않을 것 같습니다. 만약 초기값이 필요하다면, 현재 useMemo 안의 변환 로직을 컴포넌트로 옮겨야 한다는 의미였습니다.

2024-09-26 08:55 UTC, seonghunYang commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +export const useIndicatorQuote = (request: IndicatorQuoteRequest) => {
넵 수정하면 말씀해주세요!

2024-09-27 16:24 UTC, swgvenghy commented on apps/web/app/business/hooks/numerical-guidance/indicator/use-indicator-quote-view-model.hooks.ts
> +export const useIndicatorQuote = (request: IndicatorQuoteRequest) => {
[774282b](https://github.com/Fingoo-org/Fingoo/pull/282/commits/774282ba76f6fa00b3ebde3242b5bcdc759fe057)

카드 내용 변경에 필수적으로 적용되는 indicatorType, indicatorId, symbol값을 필수로 받고, 그 외에 interval같은 경우에는 해당 컴포넌트가 사용되는 부분인 MC-26부분에서 선택하니 해당 부분을 기본값을 상수로 지정하였습니다!

2024-09-30 02:26 UTC, merged