[MC-4] [web] feat: Add MiniChart component and integrate with ChartCard
Fingoo-org/Fingoo pull request #283
Opened 2024-09-12 17:31 UTC by yesolz

## ✅ 작업 내용
- MiniChart를 구현하고 ChartCard와 통합하였습니다.

## 🤔 고민 했던 부분
- 초기에는 MiniChart가 자체적으로 색상을 결정하도록 구현했으나, 준호님의 구현 사항을 반영하여 isPositive 값을 받아 색상을 결정하는 방식으로 변경했습니다.
- 차트의 stroke 컬러를 ChartCard에 사용된 컬러와 일치시키기 위해 헥스 코드를 사용했습니다.
- SparkChart라는 이름을 사용하려 했으나, 기존에 동일한 이름의 파일이 있어 MiniChart로 네이밍했습니다.

2024-09-16 09:31 UTC, swgvenghy commented
확인했습니다! 해당 코드로 도메인 컴포넌트로 만들어둔 majorIndicatorCard에도 적용해주시면 좋을 것 같아요!

2024-09-20 12:42 UTC, seonghunYang requested changes
수고하셨습니다!

2024-09-20 12:42 UTC, seonghunYang commented on apps/web/app/ui/components/view/atom/mini-chart/mini-chart.tsx
> +const MiniChart: React.FC<MiniChartProps> = ({ data, className, isPositive }) => {
[request change]
React.FC 타입을 사용한 이유가 있을까요? React.FC에는 여러 단점이 있어서 React 18에서 곧 제거될 예정입니다. 따라서 사용을 지양하는 것이 좋겠습니다.

```
({ data, className, isPositive }: MiniChartProps)
```

이렇게 쓰면 됩니다!

참고: https://github.com/facebook/create-react-app/pull/8177

2024-09-20 12:42 UTC, seonghunYang commented on apps/web/app/ui/components/view/atom/mini-chart/mini-chart.tsx
> +const MiniChart: React.FC<MiniChartProps> = ({ data, className, isPositive }) => {
[comment]
- 컴포넌트 정의하실 때 표현식을 사용하신 이유가 있을까요?

2024-09-27 18:55 UTC, yesolz commented on apps/web/app/ui/components/view/atom/mini-chart/mini-chart.tsx
> +const MiniChart: React.FC<MiniChartProps> = ({ data, className, isPositive }) => {
- 말씀해주신 React.FC의 단점 확인하였습니다!
- 준호님께서 먼저 구현하신 chart-card의 스타일에 따라 작업하여 React.FC를 사용하게 되었습니다.
- mini-chart와 기존에 있던 chart-card 부분에 사용된 React.FC 제거하였습니다!

https://github.com/Fingoo-org/Fingoo/pull/283/commits/2faba15b4680856672f4076f87dc21321fd39556

2024-09-27 19:09 UTC, yesolz commented on apps/web/app/ui/components/view/atom/mini-chart/mini-chart.tsx
> +const MiniChart: React.FC<MiniChartProps> = ({ data, className, isPositive }) => {
특별히 표현식을 사용한 이유는 없고, 이 부분도 준호님이 선작업하신 코드와 일관성을 유지하려다 보니 자연스럽게 표현식을 사용했습니다.

선언문을 사용하는 게 더 나을까요?

2024-10-03 04:48 UTC, seonghunYang commented on apps/web/app/ui/components/view/atom/mini-chart/mini-chart.tsx
> +const MiniChart: React.FC<MiniChartProps> = ({ data, className, isPositive }) => {
선언문 표현식은 스타일 차이라 괜찮을 것 같아요. 다만 제가 선언문을 조금 더 선호하는 이유는 export default 문을 사용할 수 있고, 선언문을 쓰면 호이스팅으로 함수 코드를 밑으로 내리고, 메인 코드를 먼저 파일에 노출 시킬 수 있기 때문에 좀 더 선호하긴 합니다

2024-10-03 04:48 UTC, seonghunYang approved these changes

2024-10-03 12:23 UTC, merged